# Generated by Django 4.1 on 2022-09-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DidTheyMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('date', models.TextField()),
                ('phoneNumber', models.CharField(max_length=20)),
                ('soldSinceDate', models.BooleanField(default=True)),
            ],
        ),
    ]
