# Generated by Django 4.1 on 2022-09-07 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didTheyMove', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='didtheymove',
            old_name='date',
            new_name='zipCode',
        ),
    ]
