# Generated by Django 4.1 on 2022-09-07 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didTheyMove', '0003_didtheymove_client_didtheymove_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('zipCode', models.IntegerField()),
                ('status', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Recently Sold (6)', 'Recently Sold (6)'), ('Recently Sold (12)', 'Recently Sold (12)'), ('Off Market', 'Off Market'), ('No Change', 'No Change')], default='Off Market', max_length=20)),
                ('listDate', models.DateField(blank=True)),
                ('property_id', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastChecked', models.DateField(default=datetime.date.today)),
                ('zipCode', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='didtheymove',
            name='status',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Recently Sold (6)', 'Recently Sold (6)'), ('Recently Sold (12)', 'Recently Sold (12)'), ('Off Market', 'Off Market'), ('No Change', 'No Change')], default='No Change', max_length=20),
        ),
    ]
