# Generated by Django 4.1 on 2022-09-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didTheyMove', '0005_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
    ]
